<?php
/**
 * Copyright (c) 2019-2025. Volodymyr Hryvinskyi.  All rights reserved.
 * @author: <mailto:volodymyr@hryvinskyi.com>
 * @github: <https://github.com/hryvinskyi>
 */

/**
 * @var \Hryvinskyi\InvisibleCaptcha\Block\Captcha $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

$scriptContent = <<<JS
document.getElementById('newsletter-validate-detail')
        .appendChild(document.getElementById('{$block->getWidgetId()}'));
JS;
echo $secureRenderer->renderTag(
    'script',
    [],
    $scriptContent,
    false
);
?>
<div
    class="field-recaptcha"
    data-hryvinskyi-recaptcha="target"
    data-hryvinskyi-recaptcha-target="form#newsletter-validate-detail"
    id="<?= /* @noEscape */ $block->getWidgetId() ?>"
    data-bind="scope:'invisible-captcha-newsletter'"
    data-form-id="newsletter-validate-detail"
>
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
{
    "#<?= /* @noEscape */ $block->getWidgetId() ?>": {
        "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
    }
}
</script>
