<?php
/**
 * Copyright (c) 2019. Volodymyr Hryvinskyi.  All rights reserved.
 * @author: <mailto:volodymyr@hryvinskyi.com>
 * @github: <https://github.com/hryvinskyi>
 */

/**
 * @var \Hryvinskyi\InvisibleCaptcha\Block\Captcha $block
 */
?>
<?php if ($block->isModuleOn()) : ?>
    <script type="text/javascript">
        window.reCapchaFormsToProtect = <?php echo $block->getCaptchaSelectorsJson() ?>;
        window.reCapchaSiteKey = '<?php echo $block->getSiteKey(); ?>';

        require([
            'jquery',
            'reCaptcha'
        ], function ($) {
            window.onloadCallbackGoogleRecapcha = function () {
                $.each(window.reCapchaFormsToProtect, function(k, form) {
                    $(form).reCaptcha();
                });
            };

            // Initialize Recaptcha
            if (window.reCapchaFormsToProtect.length > 0) {
                require([
                    '//www.google.com/recaptcha/api.js?onload=onloadCallbackGoogleRecapcha&render='
                    + window.reCapchaSiteKey
                ]);
            }
        });
    </script>
<?php endif; ?>
