<?php
/**
 * Copyright (c) 2019. Volodymyr Hryvinskyi.  All rights reserved.
 * @author: <mailto:volodymyr@hryvinskyi.com>
 * @github: <https://github.com/hryvinskyi>
 */

/**
 * @var $block \Hryvinskyi\InvisibleCaptcha\Block\Captcha
 */
?>

<div
    class="field-recaptcha"
    id="<?= /* @noEscape */ $block->getWidgetId() ?>"
    data-bind="scope:'invisible-captcha-newsletter'"
>
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/javascript">
    require(['jquery', 'domReady!'], function ($) {
        $('#<?= /* @noEscape */ $block->getWidgetId() ?>')
            .appendTo('#newsletter-validate-detail');
    });
</script>

<script type="text/x-magento-init">
{
    "#<?= /* @noEscape */ $block->getWidgetId() ?>": {
        "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
    }
}
</script>
