<?php
/**
 * Copyright (c) 2019. Volodymyr Hryvinskyi.  All rights reserved.
 * @author: <mailto:volodymyr@hryvinskyi.com>
 * @github: <https://github.com/hryvinskyi>
 */

/**
 * @var \Hryvinskyi\InvisibleCaptcha\Block\Captcha $block
 */
?>
<div class="field-recaptcha" id="<?php echo $block->getWidgetId() ?>" data-bind="scope:'invisible-captcha'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
{
    "#<?php echo $block->getWidgetId() ?>": {
        "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
    }
}
</script>
