<?php
/**
 * Copyright (c) 2026. Volodymyr Hryvinskyi. All rights reserved.
 * Author: Volodymyr Hryvinskyi <volodymyr@hryvinskyi.com>
 * GitHub: https://github.com/hryvinskyi
 *
 * @var \Hryvinskyi\InvisibleCaptcha\Block\CaptchaNewsletter $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

$scriptContent = <<<JS
(() => {
    const widget = document.getElementById('{$block->getWidgetId()}');
    const target = document.getElementById('newsletter-validate-detail');
    if (widget && target) {
        target.appendChild(widget);
    }
})();
JS;
echo $secureRenderer->renderTag('script', [], $scriptContent, false);
?>
<div
    class="field-recaptcha"
    data-hryvinskyi-captcha="target"
    data-hryvinskyi-captcha-target="form#newsletter-validate-detail"
    id="<?= $block->escapeHtmlAttr($block->getWidgetId()) ?>"
    data-bind="scope:'invisible-captcha-newsletter'"
    data-form-id="newsletter-validate-detail"
>
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
{
    "#<?= $block->escapeHtmlAttr($block->getWidgetId()) ?>": {
        "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
    }
}
</script>
