<?php
/**
 * Copyright (c) 2026. Volodymyr Hryvinskyi. All rights reserved.
 * Author: Volodymyr Hryvinskyi <volodymyr@hryvinskyi.com>
 * GitHub: https://github.com/hryvinskyi
 */
declare(strict_types=1);

namespace Hryvinskyi\InvisibleCaptcha\Model\Webapi {

    // The EndpointFactory is auto-generated by Magento DI. Provide a faithful
    // stand-in when running outside a compiled environment so the factory can be
    // mocked by the plugin tests below.
    if (!\class_exists(EndpointFactory::class)) {
        class EndpointFactory
        {
            public function create(array $data = []): Endpoint
            {
                return new Endpoint(
                    (string)($data['class'] ?? ''),
                    (string)($data['method'] ?? ''),
                    (string)($data['name'] ?? '')
                );
            }
        }
    }
}

namespace Hryvinskyi\InvisibleCaptcha\Test\Unit\Plugin\Webapi {

    use Hryvinskyi\InvisibleCaptcha\Api\Webapi\WebapiConfigProviderInterface;
    use Hryvinskyi\InvisibleCaptcha\Model\Webapi\Endpoint;
    use Hryvinskyi\InvisibleCaptcha\Model\Webapi\EndpointFactory;
    use Hryvinskyi\InvisibleCaptcha\Model\Webapi\TokenValidator;
    use Hryvinskyi\InvisibleCaptcha\Plugin\Webapi\GraphQlValidator;
    use Magento\Framework\App\Request\Http as HttpRequest;
    use Magento\Framework\GraphQl\Config\Element\Field;
    use Magento\Framework\GraphQl\Exception\GraphQlInputException;
    use Magento\Framework\GraphQl\Query\ResolverInterface;
    use Magento\Framework\GraphQl\Schema\Type\ResolveInfo;
    use GraphQL\Language\AST\OperationDefinitionNode;
    use PHPUnit\Framework\Attributes\DataProvider;
    use PHPUnit\Framework\MockObject\MockObject;
    use PHPUnit\Framework\TestCase;

    class GraphQlValidatorTest extends TestCase
    {
        /** @var HttpRequest&MockObject */
        private HttpRequest $request;
        /** @var WebapiConfigProviderInterface&MockObject */
        private WebapiConfigProviderInterface $configProvider;
        /** @var TokenValidator&MockObject */
        private TokenValidator $tokenValidator;
        /** @var EndpointFactory&MockObject */
        private EndpointFactory $endpointFactory;
        /** @var ResolverInterface&MockObject */
        private ResolverInterface $subject;
        /** @var Field&MockObject */
        private Field $field;
        private GraphQlValidator $plugin;

        protected function setUp(): void
        {
            $this->request = $this->createMock(HttpRequest::class);
            $this->configProvider = $this->createMock(WebapiConfigProviderInterface::class);
            $this->tokenValidator = $this->createMock(TokenValidator::class);
            $this->endpointFactory = $this->createMock(EndpointFactory::class);
            $this->subject = $this->createMock(ResolverInterface::class);

            $this->field = $this->createMock(Field::class);
            $this->field->method('getResolver')
                ->willReturn('\\Magento\\QuoteGraphQl\\Model\\Resolver\\PlaceOrder');
            $this->field->method('getName')->willReturn('placeOrder');

            $this->request->method('getHeader')->willReturn('valid-token');

            $this->plugin = new GraphQlValidator(
                $this->request,
                $this->configProvider,
                $this->tokenValidator,
                $this->endpointFactory
            );
        }

        /**
         * @return array<string, array{0: string, 1: ?string, 2: bool, 3: bool}>
         */
        public static function resolveCaseProvider(): array
        {
            return [
                // operation, formKey, tokenValid, expectException
                'non-mutation operation is skipped' => ['query', null, false, false],
                'mutation on unprotected field is skipped' => ['mutation', null, false, false],
                'mutation on protected field with invalid token throws' => ['mutation', 'place_order', false, true],
                'mutation on protected field with valid token passes' => ['mutation', 'place_order', true, false],
            ];
        }

        #[DataProvider('resolveCaseProvider')]
        public function testBeforeResolve(
            string $operation,
            ?string $formKey,
            bool $tokenValid,
            bool $expectException
        ): void {
            $resolveInfo = $this->resolveInfo($operation);

            if ($operation !== 'mutation') {
                $this->endpointFactory->expects($this->never())->method('create');
                $this->configProvider->expects($this->never())->method('getFormKeyFor');
                $this->tokenValidator->expects($this->never())->method('isValid');
            } else {
                $this->endpointFactory->method('create')->willReturnCallback(
                    static fn (array $data): Endpoint => new Endpoint(
                        (string)$data['class'],
                        (string)$data['method'],
                        (string)$data['name']
                    )
                );
                $this->configProvider->method('getFormKeyFor')->willReturn($formKey);

                if ($formKey === null) {
                    $this->tokenValidator->expects($this->never())->method('isValid');
                } else {
                    $this->tokenValidator->expects($this->once())
                        ->method('isValid')
                        ->with($formKey, 'valid-token')
                        ->willReturn($tokenValid);
                }
            }

            if ($expectException) {
                $this->expectException(GraphQlInputException::class);
            }

            $this->plugin->beforeResolve($this->subject, $this->field, null, $resolveInfo);

            // Reached only when no exception was thrown.
            $this->addToAssertionCount(1);
        }

        public function testResolverClassIsLeftTrimmedWhenBuildingEndpoint(): void
        {
            $captured = null;
            $this->endpointFactory->method('create')->willReturnCallback(
                static function (array $data) use (&$captured): Endpoint {
                    $captured = $data;

                    return new Endpoint((string)$data['class'], (string)$data['method'], (string)$data['name']);
                }
            );
            $this->configProvider->method('getFormKeyFor')->willReturn(null);

            $this->plugin->beforeResolve($this->subject, $this->field, null, $this->resolveInfo('mutation'));

            $this->assertSame('Magento\\QuoteGraphQl\\Model\\Resolver\\PlaceOrder', $captured['class']);
            $this->assertSame('resolve', $captured['method']);
            $this->assertSame('placeOrder', $captured['name']);
        }

        private function resolveInfo(string $operation): ResolveInfo
        {
            $operationNode = $this->createMock(OperationDefinitionNode::class);
            $operationNode->operation = $operation;

            $resolveInfo = $this->createMock(ResolveInfo::class);
            $resolveInfo->operation = $operationNode;

            return $resolveInfo;
        }
    }
}
