<?php
/**
 * Copyright (c) 2026. Volodymyr Hryvinskyi. All rights reserved.
 * Author: Volodymyr Hryvinskyi <volodymyr@hryvinskyi.com>
 * GitHub: https://github.com/hryvinskyi
 */
declare(strict_types=1);

namespace Hryvinskyi\InvisibleCaptcha\Model\Webapi {

    // The EndpointFactory is auto-generated by Magento DI. Provide a faithful
    // stand-in when running outside a compiled environment so the factory can be
    // mocked by the plugin tests below.
    if (!\class_exists(EndpointFactory::class)) {
        class EndpointFactory
        {
            public function create(array $data = []): Endpoint
            {
                return new Endpoint(
                    (string)($data['class'] ?? ''),
                    (string)($data['method'] ?? ''),
                    (string)($data['name'] ?? '')
                );
            }
        }
    }
}

namespace Hryvinskyi\InvisibleCaptcha\Test\Unit\Plugin\Webapi {

    use Hryvinskyi\InvisibleCaptcha\Api\Webapi\WebapiConfigProviderInterface;
    use Hryvinskyi\InvisibleCaptcha\Model\Webapi\Endpoint;
    use Hryvinskyi\InvisibleCaptcha\Model\Webapi\EndpointFactory;
    use Hryvinskyi\InvisibleCaptcha\Model\Webapi\TokenValidator;
    use Hryvinskyi\InvisibleCaptcha\Plugin\Webapi\RestValidationPlugin;
    use Magento\Framework\Webapi\Exception as WebapiException;
    use Magento\Framework\Webapi\Rest\Request as RestRequest;
    use Magento\Webapi\Controller\Rest\RequestValidator;
    use Magento\Webapi\Controller\Rest\Router;
    use Magento\Webapi\Controller\Rest\Router\Route;
    use PHPUnit\Framework\Attributes\DataProvider;
    use PHPUnit\Framework\MockObject\MockObject;
    use PHPUnit\Framework\TestCase;

    class RestValidationPluginTest extends TestCase
    {
        /** @var TokenValidator&MockObject */
        private TokenValidator $tokenValidator;
        /** @var WebapiConfigProviderInterface&MockObject */
        private WebapiConfigProviderInterface $configProvider;
        /** @var RestRequest&MockObject */
        private RestRequest $request;
        /** @var Router&MockObject */
        private Router $restRouter;
        /** @var EndpointFactory&MockObject */
        private EndpointFactory $endpointFactory;
        /** @var RequestValidator&MockObject */
        private RequestValidator $subject;
        private RestValidationPlugin $plugin;

        protected function setUp(): void
        {
            $this->tokenValidator = $this->createMock(TokenValidator::class);
            $this->configProvider = $this->createMock(WebapiConfigProviderInterface::class);
            $this->request = $this->createMock(RestRequest::class);
            $this->restRouter = $this->createMock(Router::class);
            $this->endpointFactory = $this->createMock(EndpointFactory::class);
            $this->subject = $this->createMock(RequestValidator::class);

            $route = $this->createMock(Route::class);
            $route->method('getServiceClass')->willReturn('Magento\\Quote\\Api\\CouponManagementInterface');
            $route->method('getServiceMethod')->willReturn('set');
            $route->method('getRoutePath')->willReturn('V1/carts/mine/coupons/:couponCode');
            $this->restRouter->method('match')->willReturn($route);

            $this->endpointFactory->method('create')->willReturnCallback(
                static fn (array $data): Endpoint => new Endpoint(
                    (string)$data['class'],
                    (string)$data['method'],
                    (string)$data['name']
                )
            );

            $this->request->method('getHeader')->willReturn('valid-token');

            $this->plugin = new RestValidationPlugin(
                $this->tokenValidator,
                $this->configProvider,
                $this->request,
                $this->restRouter,
                $this->endpointFactory
            );
        }

        /**
         * @return array<string, array{0: ?string, 1: bool, 2: bool}>
         */
        public static function validationCaseProvider(): array
        {
            return [
                // formKey, tokenValid, expectException
                'unprotected endpoint passes through' => [null, false, false],
                'protected endpoint with invalid token throws' => ['coupon_code', false, true],
                'protected endpoint with valid token passes' => ['coupon_code', true, false],
            ];
        }

        #[DataProvider('validationCaseProvider')]
        public function testAroundValidate(?string $formKey, bool $tokenValid, bool $expectException): void
        {
            $this->configProvider->method('getFormKeyFor')->willReturn($formKey);

            if ($formKey === null) {
                $this->tokenValidator->expects($this->never())->method('isValid');
            } else {
                $this->tokenValidator->expects($this->once())
                    ->method('isValid')
                    ->with($formKey, 'valid-token')
                    ->willReturn($tokenValid);
            }

            $proceedCount = 0;
            $proceed = function () use (&$proceedCount): void {
                $proceedCount++;
            };

            if ($expectException) {
                $this->expectException(WebapiException::class);
            }

            $this->plugin->aroundValidate($this->subject, $proceed);

            // Reached only when no exception was thrown.
            $this->assertSame(1, $proceedCount);
        }

        public function testInnerValidatorRunsBeforeCaptchaCheck(): void
        {
            // The wrapped validator must execute even for unprotected endpoints.
            $this->configProvider->method('getFormKeyFor')->willReturn(null);

            $proceedCount = 0;
            $proceed = function () use (&$proceedCount): void {
                $proceedCount++;
            };

            $this->plugin->aroundValidate($this->subject, $proceed);

            $this->assertSame(1, $proceedCount);
        }
    }
}
